### ISSUE TITLE
Analysis and Expansion of HC's

### ISSUE THREAD

**Issue by JamesTheClarke** [CntoDev/central-plaza#14]
https://www.carpenoctem.co/forums/m/26081621/viewthread/33492764-analysis-expansion-hcs/page/1

related to #6 

Goal of this initiative:

1.) document how many HCs are currently set up on our server and how many are actually running per mission, if there's a discrepancy - deploy fix

2.) expand our HC capacity by adding 1 or 2 more HCs to the server

3.) investigate if compositions (Default Modules) require an update to initiate the added HCs in the missions

**Comment by enrico-ghidoni** [comment]
@JamesTheClarke can we close this?

**Comment by enrico-ghidoni** [comment]
Closing. The Arma3 Server Launcher made by @milivojm includes a neat Headless Client count option.
