### ISSUE TITLE
Simultaneous 2nd game server instance (dev & campaigns)

### ISSUE THREAD

**Issue by milivojm** [CntoDev/central-plaza#5]
We lost our "2nd server" which was a secondary VM instance called Dev Server which was able to run a simultaneous 2nd game server instance for either continuous campaigns (e.g. anti-stasi) or testing missions with their own separate server config file, cba configs and repos, so we wouldn't always have to swap between setups on the main Private Server.

**Comment by enrico-ghidoni** [comment]
Duplicate of #13
